DROP TABLE IF EXISTS books;
DROP TABLE IF EXISTS authors;
CREATE TABLE authors(

author_id SMALLINT PRIMARY KEY AUTO_INCREMENT,
name VARCHAR(255),
age SMALLINT);




CREATE TABLE books(

author_id SMALLINT NOT NULL,
isbn VARCHAR(255),
title VARCHAR(255),


 -- Table reference
 CONSTRAINT linksAuthors FOREIGN KEY(author_id)
 REFERENCES authors(author_id)
 ON UPDATE CASCADE ON DELETE CASCADE);